### ISSUE TITLE
Make error when compiling Image

### ISSUE THREAD

**Issue by gaoshan2006** [PaddlePaddle/VisionTools#2]
Although "numpy" and "boost" have already installed in my system,  when I compile "Image'', it shows lack of numpy.hpp.  What other library or package should I installed ?  Thanks

[ 33%] Building CXX object transformer/CMakeFiles/DeJpeg.dir/PyDecodejpeg.cpp.o
In file included from /usr/lib64/python2.7/site-packages/numpy-1.11.0-py2.7-linux-ppc64le.egg/numpy/core/include/numpy/ndarraytypes.h:1777:0,
                 from /usr/lib64/python2.7/site-packages/numpy-1.11.0-py2.7-linux-ppc64le.egg/numpy/core/include/numpy/ndarrayobject.h:18,
                 from /usr/lib64/python2.7/site-packages/numpy-1.11.0-py2.7-linux-ppc64le.egg/numpy/core/include/numpy/arrayobject.h:4,
                 from /export/Paddle_image_classfication/Image/transformer/Parallel.h:17,
                 from /export/Paddle_image_classfication/Image/transformer/PyDecodejpeg.cpp:15:
/usr/lib64/python2.7/site-packages/numpy-1.11.0-py2.7-linux-ppc64le.egg/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it by " \
  ^
In file included from /export/Paddle_image_classfication/Image/transformer/PyDecodejpeg.cpp:15:0:
/export/Paddle_image_classfication/Image/transformer/Parallel.h:19:34: fatal error: boost/python/numpy.hpp: No such file or directory
 #include <boost/python/numpy.hpp>
                                  ^
compilation terminated.
make[2]: *** [transformer/CMakeFiles/DeJpeg.dir/PyDecodejpeg.cpp.o] Error 1
make[1]: *** [transformer/CMakeFiles/DeJpeg.dir/all] Error 2
make: *** [all] Error 2

**Comment by qingqing01** [comment]
>= boost_1_63_0的版本你在才有numpy，需要安装较新的boost，可以检查下版本~

**Comment by gaoshan2006** [comment]
ok. I see. Thanks a lot !

**Comment by bbaby19** [comment]
您好，我在做交通测试的时候，出现了module不存在的情况，系统是centos7，python环境是acanoda2，因为我本人不太擅长python，希望得到大神帮助！
错误如下：
 F0222 09:07:24.287128  1879 PythonUtil.cpp:186] Check failed: (module) != nullptr Current PYTHONPATH: ['/usr/local/opt/paddle/bin', '/home/bbaby19/work_place/ASC17/PaddlePaddle/benchmark_demo', '/home/bbaby19/anaconda2', '/home/bbaby19/anaconda2/lib/python2.7', '/home/bbaby19/anaconda2/lib', '/home/bbaby19/anaconda2/lib/python2.7/site-packages', '/home/bbaby19/anaconda2/lib/python27.zip', '/home/bbaby19/anaconda2/lib/python2.7/plat-linux2', '/home/bbaby19/anaconda2/lib/python2.7/lib-tk', '/home/bbaby19/anaconda2/lib/python2.7/lib-old', '/home/bbaby19/anaconda2/lib/python2.7/lib-dynload', '/home/bbaby19/anaconda2/lib/python2.7/site-packages/Sphinx-1.5.1-py2.7.egg', '/home/bbaby19/anaconda2/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg']
Python Error: <type 'exceptions.ImportError'> : No module named paddle.trainer.config_parser
Python Callstack:
Import paddle.trainer.config_parserError
*** Check failure stack trace: ***
    @           0x895c50  google::LogMessage::Fail()
    @           0x895bac  google::LogMessage::SendToLog()
    @           0x895530  google::LogMessage::Flush()
    @           0x8985d7  google::LogMessageFatal::~LogMessageFatal()
    @           0x7f46eb  paddle::py::import()
    @           0x7f475e  paddle::callPythonFuncRetPyObj()
    @           0x7f4b2c  paddle::callPythonFunc()
    @           0x71f943  paddle::TrainerConfigHelper::TrainerConfigHelper()
    @           0x71ff84  paddle::TrainerConfigHelper::createFromFlags()
    @           0x58e7d2  main
    @     0x7fad431f8b35  __libc_start_main
    @           0x59b249  (unknown)
    @              (nil)  (unknown)
/usr/local/bin/paddle: 行 109:  1879 已放弃               (吐核)${DEBUGGER} $MYDIR/../opt/paddle/bin/paddle_trainer ${@:2}
